//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mag
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagClient
    {
        public int CliendId { get; set; }
        public int TagID { get; set; }
    
        public virtual tag tag { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
