//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mag
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int id_товар { get; set; }
        public string название { get; set; }
        public Nullable<int> id_бренд { get; set; }
        public Nullable<int> id_тип { get; set; }
        public Nullable<decimal> стоимость { get; set; }
        public string Размер { get; set; }
        public Nullable<int> Страна_производства { get; set; }
        public string Пол { get; set; }
        public string состав { get; set; }
        public string Photo { get; set; }
    
        public virtual Бренд Бренд { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Пол Пол1 { get; set; }
        public virtual страна страна { get; set; }
        public virtual ТипТовара ТипТовара { get; set; }
    }
}
